[versions]
agp = "8.13.1"
androidxTextExtJunit = "1.3.0"
# @keep
compileSdk = "36"
# @keep
java = "17"
junit4 = "4.13.2"
junit5 = "5.13.4"
kotlin = "2.2.0"
ktlint = "13.0.0"
lifecycle = "2.9.2"
# @keep
minSdk = "23"
versionCatalogUpdate = "1.0.0"

[libraries]
androidx-activity = "androidx.activity:activity-ktx:1.10.1"
androidx-arch-core-runtime = "androidx.arch.core:core-runtime:2.2.0"
androidx-coordinatorlayout = "androidx.coordinatorlayout:coordinatorlayout:1.3.0"
androidx-core = "androidx.core:core-ktx:1.16.0"
androidx-fragment = "androidx.fragment:fragment-ktx:1.8.8"
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-core-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-localbroadcastmanager = "androidx.localbroadcastmanager:localbroadcastmanager:1.1.0"
androidx-resources = "androidx.appcompat:appcompat-resources:1.7.1"
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTextExtJunit" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
roboelectric = "org.robolectric:robolectric:4.15.1"
slimber = "com.github.PaulWoitaschek:Slimber:2.0.0"
w2sv-kotlinutils = "com.github.w2sv:KotlinUtils:0.1.8-rc1"

[bundles]
unitTest = [
    "androidx-test-ext-junit",
    "junit4",
    "kotlin-test-junit",
    "roboelectric",
]

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
androidJUnit5 = "de.mannodermaus.android-junit5:1.13.1.0"
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdate" }
